modLoader="javafml"
loaderVersion="[31,)" #forge version dep
issueTrackerURL="https://github.com/iChun/Clef/issues"

[[mods]]
    modId="clef"
    version="${file.jarVersion}" #mandatory
    displayName="Clef"
    displayURL="http://ichun.me/mods/clef/"
    authors="iChun"
    description='''
    𝄞
    '''

[[dependencies.clef]]
    modId="forge"
    mandatory=true
    versionRange="[31,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.clef]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2,1.16)"
    ordering="NONE"
    side="BOTH"
