modLoader="javafml"
loaderVersion="[34,)" #forge version dep
license="GNU Lesser General Public License v3.0"
issueTrackerURL="https://github.com/iChun/Clef/issues"

[[mods]]
    modId="clef"
    version="${file.jarVersion}" #mandatory
    displayName="Clef"
    displayURL="http://ichun.me/mods/clef/"
    authors="iChun, ichttt"
    description='''
    𝄞
    '''

[[dependencies.clef]]
    modId="ichunutil"
    mandatory=true
    versionRange="[10.0.0,11)"
    ordering="NONE"
    side="BOTH"
