modLoader="javafml"
loaderVersion="[31,)" #forge version dep
issueTrackerURL="https://github.com/iChun/Clef/issues"

[[mods]]
    modId="clef"
    version="${file.jarVersion}" #mandatory
    displayName="Clef"
    displayURL="http://ichun.me/mods/clef/"
    authors="iChun"
    description='''
    𝄞
    '''

[[dependencies.clef]]
    modId="ichunutil"
    mandatory=true
    versionRange="[8.0.0,9)"
    ordering="NONE"
    side="BOTH"
